'use strict';
const F=window.Festival,$=s=>document.querySelector(s);
const imageFiles={...Object.fromEntries(['chrome','sunset','risograph'].flatMap(s=>['escape','together','release'].map(t=>[`v4_${s}_${t}`,`assets/v4_${s}_${t}.png`]))),v4_chrome_escape_wander:'assets/v4_chrome_escape_wander.png',v4_chrome_escape_resonance:'assets/v4_chrome_escape_resonance.png',v4_product:'assets/v4_product.png'};
const images={};
const ready=Promise.all(Object.entries(imageFiles).map(([key,url])=>new Promise(resolve=>{const i=new Image();images[key]=i;i.onload=()=>resolve(true);i.onerror=()=>resolve(false);i.src=url;})));
const phrases=[{theme:'escape',text:'把烦恼装进气泡，今晚飞去月球',note:'白桃气泡化成通往月亮的轨迹，把想出走的心情带向远方。'},{theme:'together',text:'和朋友在海边唱到日出',note:'举起的白桃气泡水，与朋友、海风和日出一起，留下相聚的瞬间。'},{theme:'release',text:'把没喊出口的话，交给今晚的鼓点',note:'开罐的气泡汇入舞台声浪，让没说出口的情绪跟着音乐释放。'}];
let step=1,persona=null,style='chrome',phraseIndex=0,record=null,answers=[],timer=null,quizAnswers=[],quizIndex=0,quizComplete=false;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function show(view){['create','loading','result','wall'].forEach(k=>$('#'+k+'-view').hidden=k!==view);window.scrollTo({top:0,behavior:'instant'})}
function options(){$('#style-options').innerHTML=Object.entries(F.STYLES).map(([k,s])=>`<button class="choice ${style===k?'selected':''}" data-style="${k}" aria-pressed="${style===k}"><i class="swatch ${k}"></i><span><b>${s.name}</b><small>${{chrome:'夜色、霓虹与发光的气泡',sunset:'暖橙日光与柔软的梦',risograph:'纸感、色块与节奏剪影'}[k]}</small></span><span class="tick">${style===k?'✓':''}</span></button>`).join('');$('#phrase-options').innerHTML=phrases.map((p,i)=>`<button class="phrase ${i===phraseIndex?'selected':''}" data-phrase="${i}" aria-pressed="${i===phraseIndex}">${p.text}</button>`).join('')}
function renderStep(){
 document.body.dataset.step=String(step);
 [1,2,3].forEach(i=>$('#step-'+i).hidden=i!==step);
 $('#step-number').textContent=`0${step} / 03`;
 $('#step-label').textContent=['发现你的音乐人格','选你的视觉风格','留下你的音乐心情'][step-1];
 $('#back').hidden=step===1;$('#back').textContent='返回上一步';
 $('#next').disabled=false;$('#next').textContent=step===3?'生成我的专属海报':'选好了，继续';
 $('#error').textContent='';options();if(step===1)renderQuiz();
}
$('#back').onclick=()=>{
 if(step===1){if(quizComplete){quizComplete=false;quizIndex=3;persona=null;answers=[]}else if(quizIndex>0)quizIndex--;renderQuiz()}
 else{step--;renderStep()}
};
document.addEventListener('click',e=>{
 const s=e.target.closest('[data-style]'),t=e.target.closest('[data-phrase]');
 if(s){style=s.dataset.style;options()}if(t){phraseIndex=+t.dataset.phrase;options()}
});
$('#next').onclick=async()=>{if(step===1&&!quizComplete){if(!Number.isInteger(quizAnswers[quizIndex]))return;if(quizIndex<3){quizIndex++;renderQuiz()}else{const result=F.quizResult(quizAnswers);if(!result)return;persona=result.persona;answers=[...quizAnswers];quizComplete=true;renderQuiz()}return}if(step<3){step++;renderStep();return}const p=phrases[phraseIndex],result=F.create({persona,style,theme:p.theme,phrase:p.text,nickname:$('#nickname').value,answers},Math.floor(Math.random()*999999));if(!result.ok){$('#error').textContent=result.error;return}record=result.value;show('loading');$('#loading-copy').textContent=p.note;await Promise.all([ready,new Promise(r=>setTimeout(r,1600))]);if(!images[F.assetKey(record)]?.naturalWidth){show('create');$('#error').textContent='画面未能加载，请刷新后再试。';return}renderResult()};
function renderResult(){$('#poster').setAttribute('aria-label',`${record.nickname||'我的'}音乐人格海报：${record.phrase}`);window.PosterRenderer.paint($('#poster'),record,images);$('#result-heading').textContent=record.nickname?`${record.nickname}，这是你的此刻。`:'今晚的主角，是你。';$('#result-persona').textContent=F.PERSONAS[record.persona].name;$('#result-style').textContent=F.STYLES[record.style].name;$('#result-phrase').textContent=record.phrase;$('#scene-note').textContent=phrases.find(p=>p.theme===record.theme).note;$('#queue-status').textContent='';show('result')}
$('#remake').onclick=()=>{record=null;step=1;resetQuiz();renderStep();show('create')};
function showDialog(html){$('#modal-content').innerHTML=html;$('#modal').showModal()}$('#close').onclick=()=>$('#modal').close();
function qr(el,text){el.setAttribute('role','img');el.setAttribute('aria-label','扫码入口二维码');const code=qrcode(0,'M');code.addData(text);code.make();el.innerHTML=code.createSvgTag({cellSize:3,margin:4,scalable:true})}
function claimLink(){return location.href.split(/[?#]/)[0]+'?mode=claim#p='+F.encode(record)}
function download(){const a=document.createElement('a');a.download=`此刻有声_${record.nickname||'我的音乐心情'}.png`;a.href=$('#poster').toDataURL('image/png');a.click();toast('海报已发起下载，可以带走这一刻了')}
$('#save').onclick=download;
$('#qr').onclick=()=>{showDialog('<h2>把这一刻，带到手机里。</h2><p>扫码进入你的海报领取页，再保存到相册。</p><div id="claim-qr" class="qr-box"></div><p id="qr-note" class="hint"></p><button id="claim-preview" class="primary wide">查看手机领取页示例</button>');$('#qr-note').textContent=location.protocol==='file:'?'离线二维码为演示入口，可点击下方按钮查看领取页。':location.hostname==='localhost'?'本机预览二维码不能从其他手机直接访问，可查看下方领取页示例。':'扫码打开这张海报，24 小时内可领取。链接包含海报昵称和留言，请勿填写隐私。';qr($('#claim-qr'),location.protocol==='file:'?'https://example.com/shike/poster-demo':claimLink());$('#claim-preview').onclick=()=>{showDialog('<h2>你的海报，已为你留好。</h2><div class="share-preview"><img id="claim-image" alt="你的专属海报"><div><strong id="claim-name"></strong><p>1080 × 1620 高清海报<br>领取页不设倒计时</p></div></div><button id="claim-save" class="primary wide">保存我的海报</button><p>手机领取流程示例；此按钮可下载当前海报。</p>');$('#claim-image').src=$('#poster').toDataURL();$('#claim-name').textContent=record.nickname||'今晚的你';$('#claim-save').onclick=download}};
$('#share').onclick=()=>{showDialog('<h2>把你的此刻，分享给朋友。</h2><div class="share-preview"><img id="share-image" alt="分享卡片海报"><div><strong id="share-title"></strong><p id="share-copy"></p></div></div><p>分享卡片预览 · #此刻有声#</p><button id="native-share" class="primary wide">分享海报图片</button><button id="share-save" class="quiet wide">保存图片，自行发送</button><p>不会自动发布到社交平台，也不要求分享后才能领取试饮。</p>');$('#share-image').src=$('#poster').toDataURL();$('#share-title').textContent=`我的音乐人格：${F.PERSONAS[record.persona].name}`;$('#share-copy').textContent=record.phrase+'。来做一张你的音乐节海报吧。';$('#share-save').onclick=download;$('#native-share').onclick=async()=>{try{const blob=await new Promise(r=>$('#poster').toBlob(r,'image/png')),file=new File([blob],'此刻有声.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'此刻有声',text:record.phrase})}else{download();toast('图片已发起下载，请在聊天或社交平台中发送')}}catch(e){if(e.name!=='AbortError')toast('分享未完成，可以保存图片后发送')}}};
$('#reward').onclick=()=>{showDialog('<span class="event">此刻补给站</span><h2>白桃试饮券，已领取。</h2><p>凭此券到音乐节「此刻补给站」领取<br><b>此刻白桃气泡水 100 mL 试饮一份</b></p><div class="coupon-code">TAO 0911</div><p>体验券 · 非真实核销凭证<br>活动当日有效，每人限领一份，现场数量有限。</p><button id="reward-done" class="primary wide">知道了，现场见</button>');$('#reward-done').onclick=()=>$('#modal').close()};
const QKEY='shike-v4-queue';let memoryQueue=[];function readQueue(){try{return F.pruneQueue(JSON.parse(localStorage.getItem(QKEY)||'[]'))}catch{return F.pruneQueue(memoryQueue)}}function writeQueue(q){memoryQueue=q;try{localStorage.setItem(QKEY,JSON.stringify(q))}catch{}}
$('#screen').onclick=()=>{showDialog('<h2>让全场看见你的此刻？</h2><p>海报中的昵称和留言将公开展示 12 秒。最多排队 5 张，作品等候超过 10 分钟自动移出。</p><label class="consent"><input id="consent" type="checkbox"><span>我同意公开展示这张海报中的昵称、留言与画面。</span></label><button id="confirm" class="primary wide" disabled>确认申请上屏</button><p>这是本地队列演示；正式活动作品须通过审核后上屏。</p>');$('#consent').onchange=()=>$('#confirm').disabled=!$('#consent').checked;$('#confirm').onclick=()=>{const q=readQueue();if(q.some(x=>x.record.id===record.id)){toast('这张海报已在队列中');return}if(q.length>=5){toast('目前队列已满，请稍后再试；仍可保存海报');return}q.push({record,consent:true,queuedAt:Date.now()});writeQueue(q);$('#queue-status').textContent=`已加入演示队列，前方 ${q.length-1} 张作品。`;showDialog('<h2>你的心情，准备登场。</h2><p>已加入本地演示队列。轮到你时展示 12 秒，展示后自动回到品牌邀请画面。</p><button id="wall-preview" class="primary wide">查看现场大屏示例</button><button id="withdraw" class="quiet wide">撤回本次上屏申请</button>');$('#wall-preview').onclick=()=>{const u=location.href.split(/[?#]/)[0]+'?mode=wall';window.open(u,'_blank','noopener')};$('#withdraw').onclick=()=>{const pending=readQueue();if(!pending.some(x=>x.record.id===record.id)){toast('作品已离开排队，请以现场播放状态为准');return}writeQueue(pending.filter(x=>x.record.id!==record.id));$('#queue-status').textContent='已撤回上屏申请。';$('#modal').close()}}};
$('#about').onclick=()=>showDialog('<h2>此刻有声</h2><p>为虚构产品「此刻白桃气泡水」设计的音乐节体验。白桃与气泡连接你的音乐心情：气泡可以带你去月球，也能陪你和朋友碰杯，或化成现场的节奏。</p><p>回答四道音乐情境题，得到音乐人格，再选风格、留一句话，生成海报后可以保存、扫码领取、分享，也可自愿申请公开上屏。完成海报即可领试饮券，无需关注或分享。</p><p>体验版提供三句预设留言与九张风格场景，月球霓虹另有两个人格场景；其余人格会复用主场景并调整排版。昵称可编辑。没有实时生图；二维码、试饮券与公共队列是本地演示。正式活动需接入文字与图像审核、跨设备队列及核销服务。</p><p>个人创作不限时，公共上屏每张 12 秒、最多排队 5 张。昵称不应包含隐私；本地规则检查不等同于完整内容审核。</p>');
function resetQuiz(){persona=null;answers=[];quizAnswers=[];quizIndex=0;quizComplete=false}
function renderQuiz(){
 const target=$('#quiz-content');
 if(quizComplete){
  const result=F.quizResult(answers);
  target.innerHTML='<p class="quiz-count">从你的四个选择里，我们听见</p><div class="persona-reveal"><span class="persona-symbol">♫</span><h2></h2><p class="persona-line"></p></div><p class="hint quiz-reason"></p><button id="restart-quiz" class="quiet under" type="button">重新回答四个问题</button><p class="hint small">这是你此刻的音乐偏好，不是科学人格测量。</p>';
  target.querySelector('h2').textContent=F.PERSONAS[persona].name;
  target.querySelector('.persona-line').textContent=F.PERSONAS[persona].line;
  target.querySelector('.quiz-reason').textContent=result.description;
  $('#restart-quiz').onclick=()=>{resetQuiz();renderQuiz()};
  $('#next').disabled=false;$('#next').textContent='带着我的人格，选海报风格';$('#back').hidden=true;return;
 }
 const q=F.QUESTIONS[quizIndex];
 target.innerHTML=`<p class="quiz-count">音乐情境 ${quizIndex+1} / 4</p><div class="quiz-track" aria-hidden="true">${F.QUESTIONS.map((_,i)=>`<i class="${i<=quizIndex?'filled':''}"></i>`).join('')}</div><h2>${q.text}</h2><p class="hint">凭直觉选一个，没有标准答案。</p><div class="choices">${q.options.map((o,j)=>`<button class="choice ${quizAnswers[quizIndex]===j?'selected':''}" data-answer="${j}" aria-pressed="${quizAnswers[quizIndex]===j}"><span>${o.text}</span><span class="tick">${quizAnswers[quizIndex]===j?'✓':''}</span></button>`).join('')}</div>`;
 target.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{quizAnswers[quizIndex]=Number(b.dataset.answer);renderQuiz()});
 $('#next').disabled=!Number.isInteger(quizAnswers[quizIndex]);$('#next').textContent=quizIndex===3?'揭晓我的音乐人格':'下一题';
 $('#back').hidden=quizIndex===0;$('#back').textContent='上一题';
}
let paused=false,active=null,until=0,wallBusy=false;async function wallTick(){if(paused||wallBusy)return;if(active&&Date.now()<until)return;active=null;const q=readQueue();if(!q.length){$('#wall-poster').hidden=true;$('#wall-idle').hidden=false;$('#wall-status').textContent='等下一份音乐心情入场';return}active=q.shift();writeQueue(q);until=Date.now()+12000;wallBusy=true;await ready;wallBusy=false;if(paused)return;until=Date.now()+12000;PosterRenderer.paint($('#wall-poster'),active.record,images);$('#wall-poster').hidden=false;$('#wall-idle').hidden=true;$('#wall-status').textContent=`正在展示 ${active.record.nickname||'一位乐迷'} 的音乐心情 · 12 秒`;}
$('#wall-pause').onclick=()=>{paused=!paused;$('#wall-pause').textContent=paused?'继续轮播':'暂停轮播';if(paused){$('#wall-poster').hidden=true;$('#wall-idle').hidden=false;$('#wall-status').textContent='轮播已暂停，品牌邀请画面展示中'}else{active=null;wallTick()}};$('#wall-clear').onclick=()=>{writeQueue([]);active=null;paused=true;$('#wall-poster').hidden=true;$('#wall-idle').hidden=false;$('#wall-status').textContent='作品已全部下屏，轮播暂停';$('#wall-pause').textContent='继续轮播'};
$('#wall-fullscreen').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>toast('请使用浏览器全屏功能'));else document.exitFullscreen?.()};
renderStep();const mode=new URLSearchParams(location.search).get('mode');if(mode==='wall'){show('wall');$('#wall-product').src=imageFiles.v4_product;qr($('#join-qr'),location.protocol==='file:'?'https://example.com/shike':location.href.split(/[?#]/)[0]);if(navigator.locks){navigator.locks.request('shike-v4-wall',{ifAvailable:true},async lock=>{if(!lock){$('#wall-status').textContent='另一个大屏窗口正在播放，此窗口只显示活动入口。';$('#wall-pause').disabled=true;$('#wall-clear').disabled=true;return}wallTick();const interval=setInterval(wallTick,1000);await new Promise(resolve=>window.addEventListener('pagehide',resolve,{once:true}));clearInterval(interval)})}else{wallTick();setInterval(wallTick,1000)}}else if(mode==='claim'){const result=F.decode(location.hash);if(result.ok){record=result.value;ready.then(renderResult)}else{toast(result.error)}}
