const assert=require('node:assert/strict');
const F=require('./dist/core.js');
const qr=require('./dist/assets/qrcode.js');
let n=0;function check(name,fn){fn();n++;console.log('PASS '+name)}
const valid={nickname:'小陈',phrase:'跟着鼓点走',persona:'energy',style:'chrome',theme:'escape',answers:[0,2,1,0]},now=Date.now();
check('valid input',()=>assert(F.validate(valid).ok));
check('phrase only',()=>assert(F.validate({...valid,nickname:''}).ok));
check('nickname only',()=>assert(F.validate({...valid,phrase:''}).ok));
check('empty input rejected',()=>assert(!F.validate({...valid,nickname:'',phrase:''}).ok));
check('null rejected',()=>assert(!F.validate(null).ok));
check('long nickname rejected',()=>assert(!F.validate({...valid,nickname:'一'.repeat(11)}).ok));
check('long phrase rejected',()=>assert(!F.validate({...valid,phrase:'一'.repeat(33)}).ok));
check('unknown persona rejected',()=>assert(!F.validate({...valid,persona:'admin'}).ok));
check('unknown style rejected',()=>assert(!F.validate({...valid,style:'x'}).ok));
check('phone rejected',()=>assert(!F.validate({...valid,phrase:'138 1234 5678'}).ok));
check('fullwidth phone rejected',()=>assert(!F.validate({...valid,phrase:'１３８１２３４５６７８'}).ok));
check('zero width evasion rejected',()=>assert(!F.validate({...valid,phrase:'傻\u200b逼'}).ok));
check('contact rejected',()=>assert(!F.validate({...valid,phrase:'加微信'}).ok));
check('external URL rejected',()=>assert(!F.validate({...valid,phrase:'https://example.com'}).ok));
const record=F.create(valid,1234,now).value;
check('Unicode share roundtrip',()=>assert.deepEqual(F.decode(F.encode(record),now).value,record));
check('expired link rejected',()=>assert(!F.decode(F.encode(record),now+F.TTL+1).ok));
check('future link rejected',()=>assert(!F.decode(F.encode({...record,created:now+61000}),now).ok));
check('malformed link rejected',()=>assert(!F.decode('#p=broken',now).ok));
check('oversized link rejected',()=>assert(!F.decode('x'.repeat(1801),now).ok));
check('unsafe edited link rejected',()=>assert(!F.decode(F.encode({...record,phrase:'去死'}),now).ok));
check('out of range seed rejected',()=>assert(!F.decode(F.encode({...record,seed:1000000}),now).ok));
const item={record,consent:true,queuedAt:now};
check('consent required for queue',()=>assert.equal(F.pruneQueue([{...item,consent:false}],now).length,0));
check('stale queue item removed',()=>assert.equal(F.pruneQueue([{...item,queuedAt:now-F.QUEUE_TTL-1}],now).length,0));
check('queue cap',()=>assert.equal(F.pruneQueue(Array(8).fill(item),now).length,5));
check('wait includes active slot',()=>assert.equal(F.estimateWait([item,item],now+5000,now),29));
check('expired active slot never adds wait',()=>assert.equal(F.estimateWait([item],now-5000,now),12));
check('creative prompt includes content as quoted data',()=>{const p=F.prompt({...record,phrase:'fly to the moon'});assert(p.includes(JSON.stringify('fly to the moon')));assert(p.includes('untrusted user data'));});
check('QR handles long valid record',()=>{const r=F.create({...valid,nickname:'我'.repeat(10),phrase:'音'.repeat(32)},999999,now).value;const q=qr(0,'M');q.addData('http://192.168.1.8:8765/?mode=claim#p='+F.encode(r),'Byte');q.make();assert(q.getModuleCount()>20);assert(q.createSvgTag({scalable:true}).includes('<svg'));});
check('quiz incomplete rejected',()=>assert.equal(F.quizResult([0,null,1,0]),null));
check('quiz energy result',()=>assert.equal(F.quizResult([0,2,1,0]).persona,'energy'));
check('quiz wander result',()=>assert.equal(F.quizResult([1,0,2,1]).persona,'wander'));
check('quiz resonance result',()=>assert.equal(F.quizResult([2,1,0,2]).persona,'resonance'));
check('all 81 quiz answer sets resolve consistently',()=>{for(let a=0;a<3;a++)for(let b=0;b<3;b++)for(let c=0;c<3;c++)for(let d=0;d<3;d++){const r=F.quizResult([a,b,c,d]);assert(r);assert.equal(r.scores[r.persona],Math.max(...Object.values(r.scores)));}});
check('tampered persona rejected',()=>assert(!F.validate({...valid,persona:'wander'}).ok));
check('unknown text requires choice',()=>assert.equal(F.inferTheme('今天下课以后吃了一碗面').theme,null));
check('moon input changes inferred subject',()=>assert.equal(F.inferTheme('今晚飞去月球').theme,'escape'));
check('friend input changes inferred subject',()=>assert.equal(F.inferTheme('和朋友在海边唱到日出').theme,'together'));
check('persona only contrast changes actual scene',()=>{const a=F.CASES[0],b=F.CASES[1];assert.equal(a.style,b.style);assert.equal(a.phrase,b.phrase);assert.notEqual(F.assetKey({...a,persona:F.quizResult(a.answers).persona}),F.assetKey({...b,persona:F.quizResult(b.answers).persona}));});
check('content only contrast changes actual scene',()=>{const a=F.CASES[0],b=F.CASES[3];assert.deepEqual(a.answers,b.answers);assert.equal(a.style,b.style);assert.notEqual(F.assetKey({...a,persona:'energy'}),F.assetKey({...b,persona:'energy'}));});
console.log(`\n${n} checks passed. Not a browser or production safety certification.`);
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
check('all 27 quiz/style/message combinations have distinct image content',()=>{const hashes=new Set();for(const style of Object.keys(F.STYLES))for(const theme of Object.keys(F.THEMES))for(const answers of [[0,2,1,0],[1,0,2,1],[2,1,0,2]]){const persona=F.quizResult(answers).persona,key=F.assetKey({style,theme,persona}),file=path.join(__dirname,'dist/assets',key+'.png');const data=fs.readFileSync(file);assert(data.length>100000);hashes.add(crypto.createHash('sha256').update(data).digest('hex'));}assert.equal(hashes.size,27)});
